version: '2'
services:
    db: 
        image: "hub.c.163.com/library/mysql:5.7"
        container_name: mysql-container
        env_file: "/workspace/blog/mysql/db.env"
        expose:
            - "3306"
        volumes:
            - /workspace/blog/mysql/data:/var/lib/mysql
            - /workspace/blog/mysql/conf.d:/etc/mysql/conf.d

    web:
        build: .
        container_name: django-container
        depends_on:
            - db
        ports:
            - "8007:8007"
        links: 
            - db:db
        volumes:
            - /workspace/blog/my_web:/django_env
        working_dir: /django_env
        command: bash -c "python manage.py makemigrations && python manage.py migrate &&  gunicorn my_web.wsgi -c gunicorn.conf"

    nginx:
      build: ./nginx/
      container_name: blog_nginx
      ports: 
        - "80:8000"
      volumes:
        - /workspace/blog/nginx/sites-available:/etc/nginx/sites-available
        - /workspace/blog/nginx/log:/var/log/nginx
      volumes_from:
        - web:ro
      links:
        - web:web

