version: '2'
services:
    db: 
        image: "hub.c.163.com/library/mysql:5.7"
        container_name: mysql-container
        env_file: "/blog_env/mysql/db.env"
        expose:
            - "3306"
        volumes:
            - /blog_env/mysql/data:/var/lib/mysql
            - /blog_env/mysql/conf.d:/etc/mysql/conf.d

    web:
        build: .
        container_name: django-container
        depends_on:
            - db
        ports:
            - "8007:8007"
        links: 
            - db:db
        volumes:
            - /blog_env/my_web:/django_env
        working_dir: /django_env
        command: bash -c "python manage.py makemigrations && python manage.py migrate &&  gunicorn my_web.wsgi -c gunicorn.conf"

    nginx:
      build: ./nginx/
      container_name: blog_nginx
      ports: 
        - "9000:80"
      volumes:
        - /blog_env/nginx/sites-enabled:/etc/nginx/sites-enabled
        - /blog_env/nginx/log:/var/log/nginx
      volumes_from:
        - web
      depends_on:
        - web
      links:
        - web:web

