# Generated by Django 2.0.1 on 2018-03-29 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uidgenerator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('article_id', uidgenerator.models.UIDField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='文章标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('read_num', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('zan_num', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('is_publish', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tags', models.ManyToManyField(to='tag.Tag', verbose_name='所属标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
                'ordering': ['created_at'],
                'permissions': (('article_publish', 'Can Publish Article'), ('aritcle_delete', 'Can Delete Article')),
                'get_latest_by': 'created_at',
            },
        ),
    ]
