# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='path_article',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='文章地址'),
        ),
    ]
