# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-20 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name=b'\xe6\x96\x87\xe7\xab\xa0\xe5\x86\x85\xe5\xae\xb9')),
            ],
            options={
                'ordering': ['created_at'],
                'db_table': 'article_body',
                'verbose_name': '\u6587\u7ae0\u5185\u5bb9',
                'verbose_name_plural': '\u6587\u7ae0\u5185\u5bb9',
                'get_latest_by': 'created_at',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='articlebody',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe6\x96\x87\xe7\xab\xa0'),
        ),
        migrations.AddField(
            model_name='articlebody',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe4\xba\xba'),
        ),
    ]
