# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 01:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171120_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='article',
            name='read_num',
            field=models.PositiveIntegerField(default=0, verbose_name='阅读数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(null=True, to='tag.Tag', verbose_name='所属标签'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='文章标题'),
        ),
        migrations.AlterField(
            model_name='articlebody',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='articlebody',
            name='content',
            field=models.TextField(verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='articlebody',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
    ]
