# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20171206_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag', verbose_name='所属标签'),
        ),
    ]
