# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20171121_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlebody',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlebody',
            name='created_by',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='文章内容'),
        ),
        migrations.AddField(
            model_name='article',
            name='path_article',
            field=models.CharField(default='', max_length=255, verbose_name='文章地址'),
        ),
        migrations.AddField(
            model_name='article',
            name='zan_num',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='tag.Tag', verbose_name='所属标签'),
        ),
        migrations.DeleteModel(
            name='ArticleBody',
        ),
    ]
