# Generated by Django 2.0 on 2018-01-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_path_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at'], 'permissions': (('article_publish', 'Can Publish Article'), ('aritcle_delete', 'Can Delete Article')), 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
